Personajes = {
"Alex":["Hombre"," menton","Bigote"," ojos marromes"," pelo marron"],
"Alferd":["Hombre","Pelo lago","pelirojo","ojos azules","bigote"],
"Anita":["Mujer","Rubia","pelo largo","lazitos","ojos azules","sonrojada"],
"Anne":["Mujer","pelo rizo","ojos marrones","pelo marron","gorda"],
"Bernard":["Hombre","sombrero","menton","nariz grande","ojos marrones","pelo marron"],
"Bill":["Hombre","medio calvo","pelirojo","sonrojado","gordo","ojos marrones"],
"Charles":["Hombre","pelo rubio","ojos marrones","bigote rubio"],
"Claire":["Mujer","sobreo flores","peliroja","gafas azules","ojos marrones"],
"David":["Hombre","pelo rubio","ojos marrones","barba rubia"],
"Eric":["Hombre","sombrero","pelo rubio","ojos marrones", ],
"Frans":["Hombre","pelirojo","ojos marrones","pelo rizo" ],
"George":["Hombre","menton","sombrero","pelo blanco","ojos marrones","triste"],
"Herman":["Hombre","medio clavo","pelirojo","ojos marrones","nariz grande"],
"Joe":["Hombre","menton","pelo rubio","gafas rojas","ojos marrones"],
"Maria":["Mujer","sombrero","pelo marron","ojos marrones",],
"Max":["Hombre","Pelo marron","bigote","ojos marrones","pelo rizado"],
"Paul":["Hombre","menton","gafas grises","pelo blanco","ojos marrones","mayor"],
"Philip":["Hombre","pelo rizo","pelo marron","ojos marrones","barba marron"],
"Richard":["Hombre","Clavo","ojos marrones","barba","bigote"],
"Robert":["Hombre","sonrojado","menton","Pelo marron","nariz grande","ojos azules","triste"],
"Sam":["Hombre","Gafas negras","medio clavo","ojos marrones"],
"Susan":["Mujer","sonrojada","Pelo blanco y largo","lavios grandes","ojos marrones"],
"Tom":["Hombre","Gafas rojas","ojos azules","medio calvo","cara alargada"],
"Peter":["Hombre","pelo blanco","ojos azules","nariz grande",],
}